//
//  QuestionBank.swift
//  Astronomy Trivia
//
//  Created by Thomas Hill on 8/18/18.
//  Copyright © 2018 Computer Magic. All rights reserved.
//

import Foundation

class QuestionBank {
    var list = [Question]()
    init() {
        list.append(Question(question: "The Sun is approximately 93 Million miles from the Earth.", explanation: "The Sun is at an average distance of about 93,000,000 miles away from Earth. It is so far away that light from the Sun takes about 8 minutes to reach us. The Earth does not travel around the Sun in a perfect circle. This means that the distance between Earth and the Sun changes during a year.\n\nThis distance also defines the AU or Astronomical Unit. The Earth is roughly 1 AU from the Sun.", correctAnswer: true, usedImage: "SunDistance"))
//        list.append(Question(question: "The Sun is mostly made of carbon.", explanation: "The sun is mostly composed of the elements Hydrogen (H) and Helium (He). By mass the composition of the sun is 75 percent Hydrogen and 25 percent Helium. Various metals make up less than 0.1 percent of the mass of the sun.", correctAnswer: false, usedImage: "Sun"))
//        list.append(Question(question: "The AU or Astronomical Unit is a measure of an objects distance from the Sun.", explanation: "1 AU is defined as the average distance from the center of the Earth to the center of the Sun. It is the average because the Earth circles the Sun in an elliptical orbit.\n\nMercury is .39 AU from the Sun, Mars is 1.52 AU and Proxima Centauri, the closest Star to the Sun, is 268,000 AU distance from the Sun.", correctAnswer: true, usedImage: "SunDistance"))
//        list.append(Question(question: "Proxima Centauri, or Alpha Centauri C, is the closest star to the Earth.", explanation: "Sorry if you got that wrong. The Sun is the closest star to the Earth. Proxima Centauri is the closest star to our Sun. It is 4.243 light years from the Earth.\n\nProxima remains widely accepted as the closest star to Earth, but it’s still not known for certain whether Proxima is part of the Alpha Centauri system.", correctAnswer: false, usedImage: "ProximaCentauri"))
//        list.append(Question(question: "The order of the Planets from the Sun is:\n1.\tMercury\n2.\tVenus\n3.\tEarth\n4.\tMars\n5.\tJupiter\n6.\tSaturn\n7.\tUranus\n8.\tNeptune", explanation: "This order is correct", correctAnswer: true, usedImage: ""))
//        list.append(Question(question: "Neptune is the furthest planet in our Solar System from the Sun.", explanation: "Since Pluto's planet status was revoked, Neptune is the now furthest planet from the Sun at an average 30.1 AU.\n\nUranus, it's closest neighbor is almost twice as far from the Sun, 19.2 AU (Average) as it's closest neighbor, Saturn at 9.58 AU (Average).", correctAnswer: true, usedImage: "Neptune"))
//        list.append(Question(question: "Saturn is closer to the Earth than Jupiter.", explanation: "Jupiter, the 5th planet from the Sun,  is closer to the Earth than Saturn, the 6th planet from the Sun. Remember the order of the planets from a previous question.", correctAnswer: false, usedImage: "Saturn"))
//        list.append(Question(question: "Mercury, the closest planet to the Sun, is the hottest planet in our Solar System.", explanation: "Because it's atmosphere is primarily composed of carbon dioxide, Venus is the hottest planet. Think \"Global Warming.\" Mercury has no atmosphere to create this effect.", correctAnswer: false, usedImage: "Mercury"))
//        list.append(Question(question: "Uranus is the coldest planet in our Solar System.", explanation: "Because it's the furthest planet from the Sun, you would think that Neptune is the coldest, but because Uranus has little to no internal heat to supplement the heat of the sun, it is the coldest.", correctAnswer: true, usedImage: "Uranus"))
//        list.append(Question(question: "Jupiter, Saturn, Uranus and Neptune, the 4 outer planets, are made up of mostly gases with no solid surface.", explanation: "Yes, this is correct. They do have, though, solid inner cores created by the pressure of the gases above.", correctAnswer: true, usedImage: "OuterPlanets"))
//        list.append(Question(question: "The Earth orbits around the Sun twice a year.", explanation: "The Earth orbits around the Sun once a year.\n\nBecause of its elliptical orbit, the earth is closer to the sun during the northern hemisphere's winter. However, distance from the sun does not affect the seasons. The tilt of the earth's axis causes the seasons to change.", correctAnswer: false, usedImage: "EarthOrbit"))
//        list.append(Question(question: "It takes light traveling from the Sun just 8 hours to reach the Earth.", explanation: "It takes the light traveling from the Sun at 180,000 miles per second just 8 MINUTES and 20 Seconds to reach the Earth.", correctAnswer: false, usedImage: "LightToEarth"))
//        list.append(Question(question: "Mars is sometimes known as the Morning Star and Venus is sometimes known as the the Evening Star.", explanation: "Because it is the closest planet to the Earth, Venus is usually known as both the Morning Star and the Evening Star.", correctAnswer: false, usedImage: "VenusMars"))
//        list.append(Question(question: "The Moon is approximately 128,000 miles from the Earth.", explanation: "The Moon averages approximately 238,855 miles from the Earth. It took the Apollo spacecrafts 3 days each way to travel to and from the Moon.", correctAnswer: false, usedImage: "Moon"))
//        list.append(Question(question: "It is possible to have two full moons in a single month.", explanation: "Yes, the second Full Moon within a month is called a Blue Moon.", correctAnswer: true, usedImage: "BlueMoon"))
//        list.append(Question(question: "Mercury and Venus are the only two planets in our Solar System without moons.", explanation: "Yes, this correct.\n\nBecause Mercury is so close to the Sun and its gravity, it wouldn’t be able to hold on to its own moon. Any moon would most likely crash into Mercury or maybe go into orbit around the Sun and eventually get pulled into it. Why Venus doesn’t have a moon is a mystery.", correctAnswer: true, usedImage: "MercuryVenus"))
//        list.append(Question(question: "Uranus is known as a \"Rock Giant\" type planet.", explanation: "Uranus is a \"Gas Giant\" planet.", correctAnswer: false, usedImage: "Uranus"))
//        list.append(Question(question: "The Asteroid Belt is located between Jupiter and Saturn.", explanation: "The Asteroid Belt is located between Mars and Jupiter.", correctAnswer: false, usedImage: "AsteroidBelt"))
//        list.append(Question(question: "The entire surface area of Pluto is smaller than Russia.", explanation: "Yes, this is correct. Pluto is known now as an Exoplanet. There are many Exoplanets all of which reside at the outer edge of the Solar System.", correctAnswer: true, usedImage: "Pluto"))
//        list.append(Question(question: "The second full moon in a month is called a \"Harvest Moon\".", explanation: "The second full Moon is called a \"Blue Moon.\" In the Northern Hemisphere, the \"Harvest Moon\" is the closest full moon to the fall equinox, which usually occurs in mid September. A \"Witch's Moon\" is one that can be seen through the break in the clouds, or through thin clouds. It looks creepy and ominous.", correctAnswer: false, usedImage: "HarvestMoon"))
//        list.append(Question(question: "All of the giant, outer most, planets in our solar system have rings.", explanation: "The composition of the rings vary by planet.\n\nThe rings of Jupiter are mostly composed of dust. The rings of Saturn are mainly composed of ice. Little is known of the rings of Uranus and Neptune, but are beleived to be composed of dust and ice.", correctAnswer: true, usedImage: "OuterPlanets"))
//        list.append(Question(question: "Comets reside at the outer edge of the solar system in a region known as the Oort Cloud.", explanation: "When the water and gas in a comet evaporates, it leaves behind a trail of gravel. If the Earth crosses the trail, we have a meteor shower as the bits of rock enter and burn up in our atmosphere.", correctAnswer: true, usedImage: "Comet"))
//        list.append(Question(question: "The color of the outsite arc of a rainbow is blue.", explanation: "The color of the outsite arc of a rainbow is Red.\n\nRainbows appear in seven colors because water droplets break white sunlight into the seven colors of the spectrum (red, orange, yellow, green, blue, indigo, violet). You can only see a rainbow if the Sun is behind you and the rain in front.", correctAnswer: false, usedImage: "Rainbow"))
//        list.append(Question(question: "Titan is the largest moon in the Solar System.", explanation: "Titan is the largest moon of Saturn.\n\nOne of Jupiter's moons, Ganymede, is the largest moon in the Solar System. Ganymede has a diameter of 3270 miles (5,268 km) and is larger than the planet Mercury. It has a rocky core with a water/ice mantle and a crust of rock and ice.", correctAnswer: false, usedImage: "Titan"))
//        list.append(Question(question: "Isaac Newton figured out that the planets orbit in the shape of an ellipse instead of a circle.", explanation: "Johannes Kepler figured out that the planets orbit in the shape of an ellipse instead of a circle.", correctAnswer: false, usedImage: "Newton"))
    }
}
